// build.js — concatenate src/ (in fixed dependency order) into the shipped
// artifacts. Node builtins only (fs, path), per ADR-004: no bundler, no deps.
//
// Emits:
//   dist/game.js    — plain concatenated bundle (the --impl eval entry). Every
//                     module attaches to window.SI; loading it in a context
//                     where window === globalThis exposes SI.Game.
//   dist/index.html — canvas + minimal CSS shell with the bundle inlined and
//                     the ADR-003 window.gameState wiring.
const fs = require('fs');
const path = require('path');

// Dependency order. loop.js is listed before the entities because it only
// references SI.Game / SI.Renderer lazily inside functions (never at load).
const ORDER = [
  'rng.js',
  'collision.js',
  'config.js',
  'loop.js',
  'player.js',
  'bullet.js',
  'alien.js',
  'game.js',
];

const srcDir = path.join(__dirname, 'src');
const distDir = path.join(__dirname, 'dist');

const bundle = ORDER.map(function (name) {
  const body = fs.readFileSync(path.join(srcDir, name), 'utf8');
  return '// ===== src/' + name + ' =====\n' + body.trimEnd() + '\n';
}).join('\n');

fs.mkdirSync(distDir, { recursive: true });

// dist/game.js — the plain eval bundle.
const gameJs =
  '// GENERATED by build.js — do not edit. Concatenated from src/ (ADR-004).\n' +
  bundle;
fs.writeFileSync(path.join(distDir, 'game.js'), gameJs);

// dist/index.html — canvas shell + inlined bundle + gameState bootstrap.
const html = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
  '  <title>Space Invaders — slice-02</title>',
  '  <style>',
  '    html, body { margin: 0; height: 100%; background: #000; }',
  '    body { display: flex; align-items: center; justify-content: center; }',
  '    canvas { background: #000; image-rendering: pixelated; }',
  '  </style>',
  '</head>',
  '<body>',
  '  <canvas id="game" width="800" height="600"></canvas>',
  '  <script>',
  bundle,
  '',
  '    // ADR-003: expose the live state object on window for Playwright.',
  '    SI.Game.init();',
  '    window.gameState = SI.Game.state;',
  '  </script>',
  '</body>',
  '</html>',
  '',
].join('\n');
fs.writeFileSync(path.join(distDir, 'index.html'), html);

console.log('built dist/game.js and dist/index.html (' + ORDER.length + ' modules)');
